tracker_depth_node_front:
  ros__parameters:
    use_sim_time: false
    debug: false
    yolo_model: yolov8m-seg.pt
    input_topic: /front_camera/image_raw
    result_topic: /front_yolo_result
    result_image_topic: /front_yolo_image
    conf_thres: 0.25
    iou_thres: 0.45
    max_det: 300
    tracker: bytetrack.yaml
    device: ""
    result_conf: true
    result_line_width: 1
    result_font_size: 1
    result_font: Arial.ttf
    result_labels: true
    result_boxes: true
    input_depth_topic: /front_camera/depth
    camera_parameters: [487.4101257324219, 487.4101257324219, 340.6546936035156, 184.2613525390625]